version: "3.7"

services:
  mongo-dev:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATA_BASE_USER_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATA_BASE_USER_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATA_BASE_NAME}
    volumes:
      - ./mongo:/data/db
    ports:
      - '27017:27017'

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper  

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data  

volumes:
  zookeeper_data:
  kafka_data:
  mongo_data: